export const FETCH_CURRENT_MONTH_ENTRIES_SUCCESS = 'FETCH_CURRENT_MONTH_ENTRIES_SUCCESS';
export const FETCH_SPECIFIC_MONTH_ENTRIES_SUCCESS = 'FETCH_SPECIFIC_MONTH_ENTRIES_SUCCESS';
export const SET_CURRENTLY_BEIGN_EDITED = 'SET_CURRENTLY_BEIGN_EDITED';
export const EDI_CURRENTLY_BEIGN_EDITED = 'EDIT_CURRENTLY_BEIGN_EDITED';
export const CLEAR_CURRENTLY_BEIGN_EDITED = 'CLEAR_CURRENTLY_BEIGN_EDITED';

export const EDIT_CURRENTLY_BEIGN_ADDED = 'EDIT_CURRENTLY_BEIGN_ADDED';
export const CLEAR_CURRENTLY_BEIGN_ADDED = 'CLEAR_CURRENTLY_BEIGN_ADDED';

export const TOGGLE_CURRENT_MONTH = 'TOGGLE_CURRENT_MONTH';
