export const FETCH_CURRENT_MONTH_ENTRIES_SUCCESS = 'FETCH_CURRENT_MONTH_ENTRIES_SUCCESS';
export const SET_CURRENTLY_BEIGN_EDITED = 'SET_CURRENTLY_BEIGN_EDITED';
export const CHANGE_CURRENTLY_BEIGN_EDITED = 'EDIT_CURRENTLY_BEIGN_EDITED';
export const CLEAR_CURRENTLY_BEIGN_EDITED = 'CLEAR_CURRENTLY_BEIGN_EDITED';
